### ISSUE TITLE
Confused with the active-search component

### ISSUE THREAD

**Issue by Humam-Alhusaini** [haatos/goshipit#5]
I came across your library and thought it was really good for my stack. I'm confused on how to use your example on the [docs](https://goship.it/components/data_display/active_search). The CSS isn't loading and the search is not working. I'm pretty sure I followed the docs correctly, it could also be the case I didn't. I decided the best action to take is to create a seperate repo just to see if I can get it working

Please ask if you need anything. Your library is great!

My [repo](https://github.com/HumamAlhusaini/active-search)

**Comment by haatos** [comment]
If you clone the repo and launch it as is, the all components should work out of the box after installing JS dependencies with npm (by running "npm install -D" inside the repo folder). 

Please check if the CSS is being served e.g. at http://localhost:8080/static/css/tw.css. I checked the main function in your repo, and it seems to be using port 7000 when starting the app, but at least by default the settings of the app is using 8080. This could be the reason for your issue.

**Comment by Humam-Alhusaini** [comment]
I decided to clone the repo and run it. All of the components worked, which is great. It seems that it wasn't loading the CSS because I was using http://localhost:8080/active-search instead of the natural http://localhost:8080/components/data_display/active_search. It seems that this detail is related to generated/component_code_map.json, as that has the "active_search" in  http://localhost:8080/components/data_display/active_search rather than the "/active-search" in the cmd/server/main.go file. It also seems to look like it contains the html for each page (or atleast partially). How did you make this file? It looks generated.

**Comment by haatos** [comment]
/active-search is the endpoint that makes the active search example component interactive on the site. Component pages are handled by e.GET("/components/:category/:name", handler.GetComponentPage).

cmd/generate/main.go has scripts to read the source code of the project in order to display both the source code and previews of example components on the site. The results of that script are under the 'generated' folder.

**Comment by Humam-Alhusaini** [comment]
I believe I understand now. Thank you. I will attempt to figure it out tomorrow

**Comment by Humam-Alhusaini** [comment]
I'm curious, what is the purpose of  
```

 func GetActiveSearchExampleTable(c echo.Context) error {
	out := make([]templ.Component, 0, len(examples.ActiveSearchTableData))
	for _, rowData := range examples.ActiveSearchTableData {
		out = append(out, examples.ActiveSearchTableRow(
			rowData.FirstName, rowData.LastName, rowData.Email))
	}

	com := examples.ActiveSearchExample(
		"active-search-table",
		[]templ.Component{
			components.PlainText("First Name"),
			components.PlainText("Last Name"),
			components.PlainText("Email"),
		},
		out)

	return render(c, http.StatusOK, com)
}
```

in the handlers section of the [docs](https://goship.it/components/data_display/active_search)

It doesn't seem to do anything, and I can remove it from my cloned repo without losing any functionality

**Comment by haatos** [comment]
Seems like it's been left there unintentionally from a previous implementation of the component example. It is used as a handler for /active-search-table, but nothing is calling that endpoint.

**Comment by Humam-Alhusaini** [comment]
I'm pretty stumped when it comes to getting this active-search to work. Would you mind creating a small example which is similar to [GoShipIt](https://goship.it/components/data_display/active_search) where it is just a working preview that doesn't show the templ or handler?

**Comment by haatos** [comment]
> I'm pretty stumped when it comes to getting this active-search to work. Would you mind creating a small example which is similar to [GoShipIt](https://goship.it/components/data_display/active_search) where it is just a working preview that doesn't show the templ or handler?

I'm not sure what kind of example you're looking for. The active search example on the site is supposed to be the working preview of active search that you can use to build your own version.

Anyway, [here](https://github.com/haatos/active-search-example) is an example of just the necessary components to get active search working.

**Comment by Humam-Alhusaini** [comment]
Thank you very much!
